<?php
$_productCollection = Mage::getModel("catalog/product")
    ->getCollection()
    ->addAttributeToSelect('*')
    ->addAttributeToFilter('visibility', 4)
    ->addAttributeToFilter('type_id', array('eq' => 'grouped'))
    ->setPageSize(4);
?>

<ul class="room-selection-list">
    <?php foreach ($_productCollection as $_product): ?>
        <li>
            <a href="<?php echo $_product->getProductUrl()?>" class="content" style="background-image:url('<?php echo (string)Mage::helper('catalog/image')->init($_product, 'image');?>')">
            <span class="room-selection-header">
              <h3 class="room-selection-title">
                  <?php echo Mage::getModel('catalog/category')->setStoreId(Mage::app()->getStore()->getId())->load($_product->getCategoryIds()[1])->getName();?>
              </h3>
              <p>Voir la collection</p>
            </span>
            </a>
        </li>
    <?php endforeach; ?>
</ul>


